title: "Tobias Brock"
LinkedIn: "https://www.linkedin.com/in/tobias-brock-983639222/"
description: Hello, my name is Tobias, welcome to my GitHub page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Tobias-Brock.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Tobias-Brock

remote_theme: jekyll/minima@latest
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark