title: "Tobias Brock"
email: "t.brock@lmu.campus.de"
description: Hello, my name is Tobias, welcome to my GitHub page.
baseurl: ""
url: "https://Tobias-Brock.github.io"
github_username: Tobias-Brock

theme: minima
minima:
  skin: dark