title: "Tobias Brock: Projects"
email: t.brock335@googlemail.com
description: Hello, my name is Tobias, welcome to my GitHub page.
  This is a palceholder discription.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Tobias-Brock.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Tobias-Brock

# Build settings
slate:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag
